# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68995e0a18bdf61194168c4f6303991866b3b79d17944f75b8bdc756363f5d49b5820474981dcff3f66198d57a34f420436340294c7d855eceafd244f6e9b29f

test:
  secret_key_base: 3b4ba833f0fc6b40ee684037bbe7f00a5d6d2de2cb40829733f6328f163054170583d2d06a457cd3cba084b77e2860977a67db49e9033df581c895b80fe18e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
